export enum Role {
    ADMIN = 'ADMIN',
    BENIFICAIRE = 'BENIFICAIRE',
    CLIENT = 'CLIENT',
    JOBSEEKER = 'JOBSEEKER',
    SHAREHOLDER = 'SHAREHOLDER',
    DONATOR = 'DONATOR',
    INVESTOR = 'INVESTOR',
    STARTUPREPRESENTANTIVE = 'STARTUPREPRESENTANTIVE'
  }
